crearets.settings:
  type: config_object
  label: 'CREARets settings'
  mapping:
    username:
      type: string
      label: 'Username'
    password:
      type: string
      label: 'Password'
    url:
      type: string
      label: 'URL'
